# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipeProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecipeProject
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.8.2'
  pod 'SnapKit', '~> 4.2.0'
  pod 'R.swift'
  pod 'Localize-Swift', '~> 2.0'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources', '~> 4.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'ReachabilitySwift'
  pod 'IQKeyboardManagerSwift', '~> 6.2.0'
  pod 'IBAnimatable'
  pod 'NSObject+Rx'
  pod 'SwifterSwift', '~> 4.6.0'  # https://github.com/SwifterSwift/SwifterSwift
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'RxAlamofire'

end
